name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --prefer-offline --no-audit --no-update-notifier
      - run: npm run lint
      - run: npm run test:update
      - run: npm run test
      - run: npm run build
      - run: npm run build:docs
